# site settings
title: Frost Donovan
subtitle: 3D Artist
email: FrostBDonovan@gmail.com
description: Hi! I'm Frost (she/ they), an artist with a background in production and programming. I'm currently working part time as an environment and lighting artist at Octoghost Studio, and would love to find another part time role that gives me the opportunity to teach, something I found I really enjoyed through my time at uni. You can check out my <a href="https://www.artstation.com/frostdonovan">art on Artstation here,</a> <a href="\portfolio\pages\portfoliolist"> my other projects here,</a> or view a little more <a href="\portfolio\pages\aboutme">about me here.</a>
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
# street_address: 1234 Somewhere Roads
# city: Nashville
# state: TN
# zip_code: 55555
# country: United States of America
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  envelope: mailto:FrostBDonovan@gmail.com
  GitHub: https://github.com/fdonovan98
  Artstation: https://www.artstation.com/frostdonovan
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/frost-donovan
  # Twitter: https://twitter.com/eachabyss
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
